apiVersion: apps/v1
kind: Deployment
metadata:
  name: ap-nginx-login-2a
  namespace: ap
  labels:
    login: login-app-2a
spec:
  replicas: 1
  selector:
    matchLabels:
      login: login-app-2a
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        login: login-app-2a
    spec:
      containers:
      - image: 730335352888.dkr.ecr.ap-northeast-2.amazonaws.com/login:v1.3
        name: login
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 100Mi
            cpu: 100m
        volumeMounts:
        - name: pvclogin
          mountPath: /data/nginx
      volumes:
      - name: pvclogin
        persistentVolumeClaim:
          claimName: pvc-nginx
      nodeSelector:
        login: login-app-2a

---

apiVersion: v1
kind: Service
metadata:
  name: login-svc
spec:
  selector:
    login: login-app-2a
  type: NodePort
  clusterIP: 172.20.0.4
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvlogin
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: /data/nginx
    type: DirectoryOrCreate

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpe-login
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ap-nginx-login-2a
  targetCPUUtilizationPercentage: 50
