apiVersion: apps/v1
kind: Deployment
metadata:
  name: ap-nginx-sign-2c
  labels:
    sign: sign-app-2c
spec:
  replicas: 1
  selector:
    matchLabels:
      sign: sign-app-2c
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        sign: sign-app-2c
    spec:
      containers:
      - image: nginx:latest
        name: sign
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 100Mi
            cpu: 100m
        volumeMounts:
        - name: pvcsign
          mountPath: /data/nginx
      volumes:
      - name: pvcsign
        persistentVolumeClaim:
          claimName: pvc-nginx
      nodeSelector:
        sign: sign-app-2a

---

apiVersion: v1
kind: Service
metadata:
  name: sign-svc
spec:
  selector:
    sign: sign-app-2c
  type: NodePort
  clusterIP: 172.20.10.2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvsign
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: /data/nginx
    type: DirectoryOrCreate

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpe-sign
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ap-nginx-sign-2c
  targetCPUUtilizationPercentage: 50

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ap-nginx-main-2c
  labels:
    main: main-app-2c
spec:
  replicas: 3
  selector:
    matchLabels:
      main: main-app-2c
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        main: main-app-2c
    spec:
      containers:
      - image: nginx:latest
        name: main
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 100Mi
            cpu: 100m
        volumeMounts:
        - name: pvcmain
          mountPath: /data/nginx
      volumes:
      - name: pvcmain
        persistentVolumeClaim:
          claimName: pvc-nginx
      nodeSelector:
        main: main-app-2c

---

apiVersion: v1
kind: Service
metadata:
  name: main-svc
spec:
  selector:
    main: main-app-2c
  type: NodePort
  clusterIP: 172.20.10.1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvmain
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: /data/nginx
    type: DirectoryOrCreate

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpe-main
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ap-nginx-main-2c
  targetCPUUtilizationPercentage: 50

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ap-nginx-login-2c
  labels:
    login: login-app-2c
spec:
  replicas: 1
  selector:
    matchLabels:
      login: login-app-2c
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        login: login-app-2c
    spec:
      containers:
      - image: nginx:latest
        name: login
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 100Mi
            cpu: 100m
        volumeMounts:
        - name: pvclogin
          mountPath: /data/nginx
      volumes:
      - name: pvclogin
        persistentVolumeClaim:
          claimName: pvc-nginx
      nodeSelector:
        login: login-app-2c

---

apiVersion: v1
kind: Service
metadata:
  name: login-svc
spec:
  selector:
    login: login-app-2c
  type: NodePort
  clusterIP: 172.20.10.3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvlogin
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: /data/nginx
    type: DirectoryOrCreate

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpe-login
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ap-nginx-login-2c
  targetCPUUtilizationPercentage: 50

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ap-nginx-cart-2c
  labels:
    cart: cart-app-2c
spec:
  replicas: 1
  selector:
    matchLabels:
      cart: cart-app-2c
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
       cart: cart-app-2c
    spec:
      containers:
      - image: nginx:latest
        name: cart
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 100Mi
            cpu: 100m
        volumeMounts:
        - name: pvccart
          mountPath: /data/nginx
      volumes:
      - name: pvccart
        persistentVolumeClaim:
          claimName: pvc-nginx
      nodeSelector:
       cart: cart-app-2c

---

apiVersion: v1
kind: Service
metadata:
  name: cart-svc
spec:
  selector:
    cart: cart-app-2c
  type: NodePort
  clusterIP: 172.20.10.4
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvcart
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: /data/nginx
    type: DirectoryOrCreate

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpe-cart
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-nginx-cart-2c
  targetCPUUtilizationPercentage: 50
