apiVersion: apps/v1
kind: Deployment
metadata:
  name: ap-nginx-sign-2a
  labels:
    sign: sign-app-2a
spec:
  replicas: 1
  selector:
    matchLabels:
      sign: sign-app-2a
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
       sign: sign-app-2a
    spec:
      containers:
      - image: 730335352888.dkr.ecr.ap-northeast-2.amazonaws.com/sign:v1.3
        name: sign
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 100Mi
            cpu: 100m
        volumeMounts:
        - name: pvcsign
          mountPath: /data/nginx
      volumes:
      - name: pvcsign
        persistentVolumeClaim:
          claimName: pvc-nginx
      nodeSelector:
       sign: sign-app-2a

---

apiVersion: v1
kind: Service
metadata:
  name: sign-svc
spec:
  selector:
    sign: sign-app-2a
  type: NodePort
  clusterIP: 172.20.10.2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvsign
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: /data/nginx
    type: DirectoryOrCreate

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpe-sign
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-nginx-sign-2a
  targetCPUUtilizationPercentage: 50
