apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx # PersistentVolumeClaim 이름
  namespace: ap
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-was  # PersistentVolumeClaim 이름
  namespace: ap
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
